apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting; sleep 2; done']
      
      containers:
      - name: monolith
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5678

        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
